//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebCuoiKhoa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Display(Name = "User ID:")]
        public int ID { get; set; }

        [Display(Name = "Username:")]
        [Required(ErrorMessage = "Name not empty...")]
        public string NameUser { get; set; }

        [Display(Name = "User Email:")]
        [Required(ErrorMessage = "Name not empty...")]
        public string EmailUser { get; set; }

        [Display(Name = "Password:")]
        [Required(ErrorMessage = "Name not empty...")]
        public string PasswordUser { get; set; }

        [NotMapped]
        [Display(Name = "Nhập lại Password:")]
        public string ConfirmPass { get; set; }

    }
}