//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebCuoiKhoa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            ImagePro = "~/image/add.png";
        }
       
        public int ProductID { get; set; }
        public string NamePro { get; set; }
        public string NameCPU { get; set; }
        public string Core { get; set; }
        public string Thread { get; set; }
        public string BusCPU { get; set; }
        public string VGA { get; set; }
        public string Storage { get; set; }
        public string RAM { get; set; }
        public string BusRam { get; set; }
        public string MaxRam { get; set; }
        public string Resolution { get; set; }
        public string Nen { get; set; }
        public string Monitor { get; set; }
        public string Port { get; set; }
        public string Webcam { get; set; }
        public string KeyboardLight { get; set; }
        public string Tinhnangkhac { get; set; }
        public string DecriptionPro { get; set; }
        public string IDCate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImagePro { get; set; }

        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
